-- MySQL Script generated by MySQL Workbench
-- 05/17/17 21:45:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aredespacio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aredespacio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aredespacio` DEFAULT CHARACTER SET utf8 ;
USE `aredespacio` ;

-- -----------------------------------------------------
-- Table `aredespacio`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`alumno` (
  `idAlumno` INT(11) NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `movil` VARCHAR(45) NOT NULL,
  `domicilo` VARCHAR(45) NOT NULL,
  `cp` VARCHAR(45) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `foto` LONGBLOB NULL DEFAULT NULL,
  `fechaRegistro` DATE NOT NULL,
  `fechaBaja` DATE NULL DEFAULT NULL,
  `status` VARCHAR(10) NOT NULL DEFAULT 'Alta',
  `motivo` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idAlumno`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aredespacio`.`maestro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`maestro` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `noDeColaborador` VARCHAR(12) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `foto` LONGBLOB NULL DEFAULT NULL,
  `fechaDeNacimiento` DATE NOT NULL,
  `genero` TINYINT(1) NOT NULL,
  `correoElectronico` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `telefonoMovil` VARCHAR(45) NOT NULL,
  `domicilio` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `codigoPostal` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `fechaDeRegistro` DATE NOT NULL,
  `deshabilitado` TINYINT(1) NOT NULL,
  `fechaDeDeshabilitacion` DATE NULL DEFAULT NULL,
  `motivoDeDeshabilitacion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aredespacio`.`danza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`danza` (
  `idDanza` INT(11) NOT NULL AUTO_INCREMENT,
  `tipoDanza` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDanza`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`grupo` (
  `idGrupo` INT(11) NOT NULL AUTO_INCREMENT,
  `salon` VARCHAR(10) NOT NULL,
  `idMaestro` INT(11) NOT NULL,
  `idDanza` INT(11) NOT NULL,
  `nivel` VARCHAR(45) NOT NULL,
  `inicioDeGrupo` DATE NOT NULL,
  `finDeGrupo` DATE NULL DEFAULT NULL,
  `costo` INT(11) NOT NULL,
  `porcentaje` INT(11) NOT NULL,
  PRIMARY KEY (`idGrupo`),
  INDEX `idMaestro` (`idMaestro` ASC),
  INDEX `idDanza` (`idDanza` ASC),
  CONSTRAINT `grupo_ibfk_1`
    FOREIGN KEY (`idMaestro`)
    REFERENCES `aredespacio`.`maestro` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `grupo_ibfk_2`
    FOREIGN KEY (`idDanza`)
    REFERENCES `aredespacio`.`danza` (`idDanza`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aredespacio`.`clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`clase` (
  `idClase` INT(11) NOT NULL AUTO_INCREMENT,
  `idGrupo` INT(11) NOT NULL,
  `idAlumno` INT(11) NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  PRIMARY KEY (`idClase`),
  UNIQUE INDEX `idClase` USING BTREE (`idClase` ASC),
  INDEX `idGrupo` USING BTREE (`idGrupo` ASC),
  INDEX `idAlumno` USING BTREE (`idAlumno` ASC),
  CONSTRAINT `clase_ibfk_1`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `aredespacio`.`alumno` (`idAlumno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `clase_ibfk_2`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `aredespacio`.`grupo` (`idGrupo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aredespacio`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`asistencia` (
  `idAsistencia` INT(11) NOT NULL AUTO_INCREMENT,
  `idClase` INT(11) NULL DEFAULT NULL,
  `asistio` BIT(1) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idAsistencia`),
  INDEX `idClase` (`idClase` ASC),
  CONSTRAINT `asistencia_ibfk_1`
    FOREIGN KEY (`idClase`)
    REFERENCES `aredespacio`.`clase` (`idClase`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`contador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`contador` (
  `idContador` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `contador` INT(11) NOT NULL,
  PRIMARY KEY (`idContador`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aredespacio`.`egreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`egreso` (
  `idPago` INT(11) NOT NULL AUTO_INCREMENT,
  `monto` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `motivo` TEXT NOT NULL,
  `IdMaestro` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idPago`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aredespacio`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`horario` (
  `idHorario` INT(11) NOT NULL AUTO_INCREMENT,
  `idGrupo` INT(11) NOT NULL,
  `dia` VARCHAR(10) NOT NULL,
  `hora` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idHorario`),
  INDEX `idGrupo` (`idGrupo` ASC),
  CONSTRAINT `horario_ibfk_1`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `aredespacio`.`grupo` (`idGrupo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aredespacio`.`promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`promocion` (
  `idPromocion` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(60) NOT NULL,
  `descuento` FLOAT NOT NULL,
  PRIMARY KEY (`idPromocion`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`pago` (
  `idPago` INT(11) NOT NULL AUTO_INCREMENT,
  `idPromocion` INT(11) NOT NULL,
  `folio` VARCHAR(12) NOT NULL,
  `idClase` INT(11) NOT NULL,
  `descuento` FLOAT NOT NULL,
  `abono` FLOAT NOT NULL,
  `fechaPago` DATE NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `tipoDePago` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `idClase` (`idClase` ASC),
  INDEX `idPromocion` (`idPromocion` ASC),
  CONSTRAINT `pago_ibfk_1`
    FOREIGN KEY (`idClase`)
    REFERENCES `aredespacio`.`clase` (`idClase`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pago_ibfk_2`
    FOREIGN KEY (`idPromocion`)
    REFERENCES `aredespacio`.`promocion` (`idPromocion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
