<<<<<<< HEAD
-- MySQL Script generated by MySQL Workbench
-- 05/17/17 21:45:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aredespacio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aredespacio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aredespacio` DEFAULT CHARACTER SET utf8 ;
USE `aredespacio` ;

-- -----------------------------------------------------
-- Table `aredespacio`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`alumno` (
  `idAlumno` INT(11) NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `movil` VARCHAR(45) NOT NULL,
  `domicilo` VARCHAR(45) NOT NULL,
  `cp` VARCHAR(45) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `foto` LONGBLOB NULL DEFAULT NULL,
  `fechaRegistro` DATE NOT NULL,
  `fechaBaja` DATE NULL DEFAULT NULL,
  `status` VARCHAR(10) NOT NULL DEFAULT 'Alta',
  `motivo` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idAlumno`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aredespacio`.`maestro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`maestro` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `noDeColaborador` VARCHAR(12) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `foto` LONGBLOB NULL DEFAULT NULL,
  `fechaDeNacimiento` DATE NOT NULL,
  `genero` TINYINT(1) NOT NULL,
  `correoElectronico` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `telefonoMovil` VARCHAR(45) NOT NULL,
  `domicilio` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `codigoPostal` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `fechaDeRegistro` DATE NOT NULL,
  `deshabilitado` TINYINT(1) NOT NULL,
  `fechaDeDeshabilitacion` DATE NULL DEFAULT NULL,
  `motivoDeDeshabilitacion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aredespacio`.`danza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`danza` (
  `idDanza` INT(11) NOT NULL AUTO_INCREMENT,
  `tipoDanza` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDanza`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`grupo` (
  `idGrupo` INT(11) NOT NULL AUTO_INCREMENT,
  `salon` VARCHAR(10) NOT NULL,
  `idMaestro` INT(11) NOT NULL,
  `idDanza` INT(11) NOT NULL,
  `nivel` VARCHAR(45) NOT NULL,
  `inicioDeGrupo` DATE NOT NULL,
  `finDeGrupo` DATE NULL DEFAULT NULL,
  `costo` INT(11) NOT NULL,
  `porcentaje` INT(11) NOT NULL,
=======
/*
Navicat MySQL Data Transfer

Source Server         : MySQL Server
Source Server Version : 50718
Source Host           : 127.0.0.1:3306
Source Database       : aredespacio

Target Server Type    : MYSQL
Target Server Version : 50718
File Encoding         : 65001

Date: 2017-05-16 03:05:50
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for alumno
-- ----------------------------
DROP TABLE IF EXISTS `alumno`;
CREATE TABLE `alumno` (
  `idAlumno` int(11) NOT NULL AUTO_INCREMENT,
  `matricula` varchar(45) NOT NULL,
  `nombre` varchar(45) NOT NULL,
  `apellidos` varchar(45) NOT NULL,
  `fechaNacimiento` date NOT NULL,
  `genero` varchar(45) NOT NULL,
  `correo` varchar(45) DEFAULT NULL,
  `telefono` varchar(45) DEFAULT NULL,
  `movil` varchar(45) NOT NULL,
  `domicilo` varchar(45) NOT NULL,
  `cp` varchar(45) DEFAULT NULL,
  `ciudad` varchar(45) NOT NULL,
  `estado` varchar(45) NOT NULL,
  `foto` longblob,
  `fechaRegistro` date NOT NULL,
  `fechaBaja` date DEFAULT NULL,
  `status` varchar(10) NOT NULL DEFAULT 'Alta',
  `motivo` text,
  PRIMARY KEY (`idAlumno`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for asistencia
-- ----------------------------
DROP TABLE IF EXISTS `asistencia`;
CREATE TABLE `asistencia` (
  `idAsistencia` int(11) NOT NULL AUTO_INCREMENT,
  `idClase` int(11) NOT NULL,
  `asistio` bit(1) NOT NULL,
  `fecha` date NOT NULL,
  PRIMARY KEY (`idAsistencia`),
  KEY `idClase` (`idClase`),
  CONSTRAINT `asistencia_ibfk_1` FOREIGN KEY (`idClase`) REFERENCES `clase` (`idClase`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for clase
-- ----------------------------
DROP TABLE IF EXISTS `clase`;
CREATE TABLE `clase` (
  `idClase` int(11) NOT NULL AUTO_INCREMENT,
  `idGrupo` int(11) NOT NULL,
  `idAlumno` int(11) NOT NULL,
  `fechaRegistro` date NOT NULL,
  PRIMARY KEY (`idClase`),
  UNIQUE KEY `idClase` (`idClase`) USING BTREE,
  KEY `idGrupo` (`idGrupo`) USING BTREE,
  KEY `idAlumno` (`idAlumno`) USING BTREE,
  CONSTRAINT `clase_ibfk_1` FOREIGN KEY (`idAlumno`) REFERENCES `alumno` (`idAlumno`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `clase_ibfk_2` FOREIGN KEY (`idGrupo`) REFERENCES `grupo` (`idGrupo`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for danza
-- ----------------------------
DROP TABLE IF EXISTS `danza`;
CREATE TABLE `danza` (
  `idDanza` int(11) NOT NULL AUTO_INCREMENT,
  `tipoDanza` varchar(45) NOT NULL,
  PRIMARY KEY (`idDanza`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for egreso
-- ----------------------------
DROP TABLE IF EXISTS `egreso`;
CREATE TABLE `egreso` (
  `idEgreso` int(11) NOT NULL AUTO_INCREMENT,
  `monto` int(11) NOT NULL,
  `fecha` date NOT NULL,
  `motivo` text NOT NULL,
  `IdMaestro` int(11) DEFAULT NULL,
  PRIMARY KEY (`idEgreso`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for grupo
-- ----------------------------
DROP TABLE IF EXISTS `grupo`;
CREATE TABLE `grupo` (
  `idGrupo` int(11) NOT NULL AUTO_INCREMENT,
  `salon` varchar(10) NOT NULL,
  `idMaestro` int(11) NOT NULL,
  `idDanza` int(11) NOT NULL,
  `nivel` varchar(45) NOT NULL,
  `inicioDeGrupo` date NOT NULL,
  `finDeGrupo` date DEFAULT NULL,
  `costo` int(11) NOT NULL,
  `porcentaje` int(11) NOT NULL,
>>>>>>> e2dd2ce3f08e41e4e79bbdb1827f7be6c6368d25
  PRIMARY KEY (`idGrupo`),
  INDEX `idMaestro` (`idMaestro` ASC),
  INDEX `idDanza` (`idDanza` ASC),
  CONSTRAINT `grupo_ibfk_1`
    FOREIGN KEY (`idMaestro`)
    REFERENCES `aredespacio`.`maestro` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `grupo_ibfk_2`
    FOREIGN KEY (`idDanza`)
    REFERENCES `aredespacio`.`danza` (`idDanza`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aredespacio`.`clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`clase` (
  `idClase` INT(11) NOT NULL AUTO_INCREMENT,
  `idGrupo` INT(11) NOT NULL,
  `idAlumno` INT(11) NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  PRIMARY KEY (`idClase`),
  UNIQUE INDEX `idClase` USING BTREE (`idClase` ASC),
  INDEX `idGrupo` USING BTREE (`idGrupo` ASC),
  INDEX `idAlumno` USING BTREE (`idAlumno` ASC),
  CONSTRAINT `clase_ibfk_1`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `aredespacio`.`alumno` (`idAlumno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `clase_ibfk_2`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `aredespacio`.`grupo` (`idGrupo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aredespacio`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`asistencia` (
  `idAsistencia` INT(11) NOT NULL AUTO_INCREMENT,
  `idClase` INT(11) NULL DEFAULT NULL,
  `asistio` BIT(1) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idAsistencia`),
  INDEX `idClase` (`idClase` ASC),
  CONSTRAINT `asistencia_ibfk_1`
    FOREIGN KEY (`idClase`)
    REFERENCES `aredespacio`.`clase` (`idClase`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`contador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`contador` (
  `idContador` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `contador` INT(11) NOT NULL,
  PRIMARY KEY (`idContador`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aredespacio`.`egreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`egreso` (
  `idPago` INT(11) NOT NULL AUTO_INCREMENT,
  `monto` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `motivo` TEXT NOT NULL,
  `IdMaestro` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idPago`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aredespacio`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`horario` (
  `idHorario` INT(11) NOT NULL AUTO_INCREMENT,
  `idGrupo` INT(11) NOT NULL,
  `dia` VARCHAR(10) NOT NULL,
  `hora` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idHorario`),
<<<<<<< HEAD
  INDEX `idGrupo` (`idGrupo` ASC),
  CONSTRAINT `horario_ibfk_1`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `aredespacio`.`grupo` (`idGrupo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aredespacio`.`promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`promocion` (
  `idPromocion` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(60) NOT NULL,
  `descuento` FLOAT NOT NULL,
  PRIMARY KEY (`idPromocion`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aredespacio`.`pago` (
  `idPago` INT(11) NOT NULL AUTO_INCREMENT,
  `idPromocion` INT(11) NOT NULL,
  `folio` VARCHAR(12) NOT NULL,
  `idClase` INT(11) NOT NULL,
  `descuento` FLOAT NOT NULL,
  `abono` FLOAT NOT NULL,
  `fechaPago` DATE NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `tipoDePago` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `idClase` (`idClase` ASC),
  INDEX `idPromocion` (`idPromocion` ASC),
  CONSTRAINT `pago_ibfk_1`
    FOREIGN KEY (`idClase`)
    REFERENCES `aredespacio`.`clase` (`idClase`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pago_ibfk_2`
    FOREIGN KEY (`idPromocion`)
    REFERENCES `aredespacio`.`promocion` (`idPromocion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
=======
  KEY `idGrupo` (`idGrupo`),
  CONSTRAINT `horario_ibfk_1` FOREIGN KEY (`idGrupo`) REFERENCES `grupo` (`idGrupo`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for maestro
-- ----------------------------
DROP TABLE IF EXISTS `maestro`;
CREATE TABLE `maestro` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `noDeColaborador` varchar(12) NOT NULL,
  `nombre` varchar(45) NOT NULL,
  `apellidos` varchar(45) NOT NULL,
  `foto` longblob,
  `fechaDeNacimiento` date NOT NULL,
  `genero` tinyint(1) NOT NULL,
  `correoElectronico` varchar(45) DEFAULT NULL,
  `telefono` varchar(45) DEFAULT NULL,
  `telefonoMovil` varchar(45) NOT NULL,
  `domicilio` varchar(45) NOT NULL,
  `ciudad` varchar(45) NOT NULL,
  `codigoPostal` varchar(45) DEFAULT NULL,
  `estado` varchar(45) NOT NULL,
  `fechaDeRegistro` date NOT NULL,
  `deshabilitado` tinyint(1) NOT NULL,
  `fechaDeDeshabilitacion` date DEFAULT NULL,
  `motivoDeDeshabilitacion` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for pago
-- ----------------------------
DROP TABLE IF EXISTS `pago`;
CREATE TABLE `pago` (
  `idPago` int(11) NOT NULL AUTO_INCREMENT,
  `idPromocion` int(11) NOT NULL,
  `folio` varchar(12) NOT NULL,
  `idClase` int(11) NOT NULL,
  `descuento` float NOT NULL,
  `abono` float NOT NULL,
  `fechaPago` date NOT NULL,
  `status` varchar(10) NOT NULL,
  `tipoDePago` varchar(32) NOT NULL,
  PRIMARY KEY (`idPago`),
  KEY `idClase` (`idClase`),
  KEY `idPromocion` (`idPromocion`),
  CONSTRAINT `pago_ibfk_1` FOREIGN KEY (`idClase`) REFERENCES `clase` (`idClase`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `pago_ibfk_2` FOREIGN KEY (`idPromocion`) REFERENCES `promocion` (`idPromocion`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for promocion
-- ----------------------------
DROP TABLE IF EXISTS `promocion`;
CREATE TABLE `promocion` (
  `idPromocion` int(11) NOT NULL AUTO_INCREMENT,
  `tipo` varchar(20) NOT NULL,
  `descripcion` varchar(60) NOT NULL,
  `descuento` float NOT NULL,
  PRIMARY KEY (`idPromocion`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8;
>>>>>>> e2dd2ce3f08e41e4e79bbdb1827f7be6c6368d25
